#!/usr/bin/env python2.7

import os
import sys

_APP_PATH = \
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        '..', '..', '..')

sys.path.insert(0, _APP_PATH)

import logging
import argparse
import json

import mci.config.log
import mci.images

_LOGGER = logging.getLogger(__name__)

def _main():
    mci.config.log.configure(True)

    i = mci.images.Images()

    duplicates = i.duplicate_images_gen()
    i.remove_duplicates(duplicates)

if __name__ == '__main__':
    _main()
