#!/usr/bin/env python2.7

import os
import sys

_APP_PATH = \
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        '..', '..', '..')

sys.path.insert(0, _APP_PATH)

import logging
import argparse
import tabulate

import mci.config.log
import mci.images

_LOGGER = logging.getLogger(__name__)

def _get_args():
    description = "Print a list of the images for a product"
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument(
        'product_id',
        type=int,
        help="Product ID")

    args = parser.parse_args()
    return args

def _main():
    mci.config.log.configure(True)

    args = _get_args()

    product_id = args.product_id

    i = mci.images.Images()
    images = i.images_gen(product_id)
    images = list(images)

    if not images:
        print("No images found.")
    else:
        distilled = [(i + 1, image['label'], image['url'], image['position'], image['types']) for i, image in enumerate(images)]

        headers = ['', 'Label', 'URL', 'position', 'types']
        print(tabulate.tabulate(distilled, headers=headers))
        print('')

if __name__ == '__main__':
    _main()
